### ISSUE TITLE
Missing okta_auth.js

### ISSUE THREAD

**Issue by sobotklp** [GuiTeK/aws-s3-oauth2-okta#1]
Hi there,

Thanks for the walkthrough! Looking through the repo tho, it looks like there are some missing .js files that implement the actual Lambda@Edge function, e.g. okta_auth.js

Would it be possible to commit those?

**Comment by GuiTeK** [comment]
Hi @sobotklp,

`okta_auth.js` is generated by Terraform from [okta_auth.js.tpl](https://github.com/GuiTeK/aws-s3-oauth2-okta/blob/main/module/okta_auth.js.tpl) (using templates was needed to pass some dynamic values from Terraform to the Lambda because Lambda@Edge doesn't support environment variables).

I'm closing this issue, feel free to open a new one if you have other questions 👍🏻
